### PR TITLE
SimpleStyle support

### PR DESCRIPTION
**Pull request by Zverik**
You can have task with big feature collections inside them: lines, polygons, markers. This PR adds a styling function, so that these features can look different, helping make sense of them.

Specification is here: https://github.com/mapbox/simplestyle-spec

Note: PR is not tested. I'd be happy if you could run it and see if it works, or wait until I manage to start the backend server.

### CODE REVIEW

**Comment by nrotstan** [comment]
This is a great idea, @Zverik, thank you!

**Comment by nrotstan** [comment]
@Zverik do you have a sample geojson file?

**Comment by Zverik** [comment]
Yes, try [this one](http://textual.ru/mapr100.json): it has a few FeatureCollections for tasks, at least the first one should load fine.

**Comment by nrotstan** [comment]
I made a couple changes and have it working, @Zverik. Can you give me access to your fork so I can push to the PR?

**Pull request merged**
